import type {
  CodebaseAnalysis,
  ExistingRule,
  GitAnalysis,
  SessionAnalysis,
} from "../types";

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Build the LLM prompt that asks the model to generate a project-specific
 * playbook from the raw analysis data.
 *
 * The returned string is intended to be sent to the current model via
 * `pi.sendUserMessage()`.
 */
export function generatePlaybookPrompt(
  gitAnalysis: GitAnalysis | null,
  sessionAnalysis: SessionAnalysis | null,
  codebaseAnalysis: CodebaseAnalysis
): string {
  const sections: string[] = [];

  // -- Instruction header ---------------------------------------------------
  sections.push(trimBlock(`
    Generate a project-specific prompt playbook in Markdown format.
    Use the analysis data below to fill every section with REAL, SPECIFIC
    information from this project.  Use actual file paths, actual command
    names, actual framework conventions.  Do NOT be generic.

    Output ONLY the Markdown playbook — no preamble, no explanation.
  `));

  // -- Playbook template structure ------------------------------------------
  sections.push(trimBlock(`
    ## Playbook Template

    Follow this exact structure:

    \`\`\`markdown
    # Project Playbook
    > Auto-generated by pi-prompt-playbook-boost. Last updated: {{DATE}}
    > Based on: {{COMMIT_COUNT}} commits, {{SESSION_COUNT}} sessions, {{FILE_COUNT}} source files

    ## Project Identity
    - **Stack**: {{STACK}}
    - **Test runner**: {{TEST_RUNNER}}
    - **Package manager**: {{PKG_MANAGER}}
    - **Monorepo**: {{MONOREPO}}
    - **Key directories**: {{KEY_DIRS}}

    ## Prompt Structure

    ### 1. WHAT — Clear Deliverable
    State exactly what to build. Be specific about the end result.

    ### 2. WHERE — File Locations
    Name the files to create or modify.

    ### 3. CONNECTS — Integration Points
    List every system this feature touches.
    [Project-specific examples from the stack.]

    ### 4. GUARDS — Constraints & Edge Cases
    State what must NOT happen, validation rules, error cases.

    ### 5. VERIFY — Definition of Done
    How to confirm the work is complete.
    [Project-specific verification commands.]

    ## Mandatory Checklist
    [Auto-generated from failure analysis — items that when omitted cause fixes]
    - [ ] Item 1
    - [ ] Item 2

    ## Conventions
    [Auto-extracted from codebase and existing rules]
    - Convention 1
    - Convention 2

    ## Co-Change Rules
    [From git coupling analysis]
    - When modifying X → also update Y
    - ...

    ## Known Failure Patterns
    [From fix-after-feature chain analysis]
    - Pattern → caused N fix commits

    ## AI-Specific Anti-Patterns
    [Things the AI specifically gets wrong in this project]
    - Anti-pattern 1

    ## Success Patterns
    [Prompt structures that historically led to clean first-attempt code]
    - Pattern → success rate

    ## Stats
    - Total boosted prompts: 0
    - First-attempt success rate: N/A
    - Most effective template: N/A
    - Most problematic area: N/A
    - Last updated: {{DATE}}
    \`\`\`
  `));

  // -- Raw analysis data ----------------------------------------------------
  sections.push("## Analysis Data\n");
  sections.push(gitAnalysis ? formatGitAnalysis(gitAnalysis) : "### Git History\nNo git history available (new project).\n");
  sections.push(sessionAnalysis ? formatSessionAnalysis(sessionAnalysis) : "### Pi Sessions\nNo session history available.\n");
  sections.push(formatCodebaseAnalysis(codebaseAnalysis));

  // -- Final instructions ---------------------------------------------------
  sections.push(trimBlock(`
    ## Instructions

    1. Replace every {{PLACEHOLDER}} with real data from the analysis above.
    2. For "Mandatory Checklist": derive items from the fix chains — each
       recurring fix pattern becomes a checklist item.
    3. For "Conventions": merge data from the tech stack, existing rules, and
       file patterns.  Be specific (e.g. "Use \`@/\` import alias" not
       "Use consistent imports").
    4. For "Co-Change Rules": translate coupling rules into actionable
       sentences (e.g. "When modifying prisma/schema.prisma → run prisma
       generate").
    5. For "Known Failure Patterns": convert fix chains into warnings with
       real file paths and counts.
    6. For "Success Patterns": use clean commit rate and session data to
       identify what works.
    7. For "AI-Specific Anti-Patterns": infer from session retries and tool
       errors what the AI commonly gets wrong.
    8. If a section has no data (e.g. no sessions yet), write:
       "No data yet — this section populates as you work."
    9. Keep the playbook under 10 KB.  Be dense, not verbose.
  `));

  return sections.join("\n\n");
}

/**
 * Build a concise, human-readable summary of the analysis results.
 * Shown to the user as a notification after setup completes.
 */
export function buildAnalysisSummary(
  gitAnalysis: GitAnalysis | null,
  sessionAnalysis: SessionAnalysis | null,
  codebaseAnalysis: CodebaseAnalysis
): string {
  const lines: string[] = [];

  // Stack
  const stackParts: string[] = [];
  if (codebaseAnalysis.stack.language !== "unknown")
    stackParts.push(codebaseAnalysis.stack.language);
  if (codebaseAnalysis.stack.framework)
    stackParts.push(codebaseAnalysis.stack.framework);
  if (codebaseAnalysis.stack.orm) stackParts.push(codebaseAnalysis.stack.orm);
  if (codebaseAnalysis.stack.styling)
    stackParts.push(codebaseAnalysis.stack.styling);

  if (stackParts.length > 0) {
    lines.push(`Tech stack: ${stackParts.join(", ")}`);
  }

  if (codebaseAnalysis.testFramework) {
    lines.push(`Test framework: ${codebaseAnalysis.testFramework}`);
  }

  // Git
  if (gitAnalysis && gitAnalysis.totalCommits > 0) {
    lines.push(
      `${gitAnalysis.totalCommits} commits analyzed` +
        ` → ${gitAnalysis.fixChains.length} fix-after-feature chains found`
    );
  } else {
    lines.push("No git history (new project)");
  }

  // Sessions
  if (sessionAnalysis && sessionAnalysis.totalSessions > 0) {
    lines.push(
      `${sessionAnalysis.totalSessions} pi sessions` +
        ` → ${sessionAnalysis.totalUserMessages} prompts analyzed`
    );
  } else {
    lines.push("No pi session history found");
  }

  // Coupling rules
  if (gitAnalysis && gitAnalysis.couplingRules.length > 0) {
    lines.push(
      `${gitAnalysis.couplingRules.length} co-change coupling rules detected`
    );
  }

  // Existing rules
  if (codebaseAnalysis.existingRules.length > 0) {
    const sources = codebaseAnalysis.existingRules.map(
      (r: { source: string }) => r.source
    );
    lines.push(`Existing rules imported from: ${sources.join(", ")}`);
  }

  // Linter config
  if (codebaseAnalysis.linterConfig) {
    lines.push(`Linter: ${codebaseAnalysis.linterConfig.tool}`);
  }

  // CI workflows
  if (codebaseAnalysis.ciWorkflows.length > 0) {
    lines.push(
      `${codebaseAnalysis.ciWorkflows.length} CI workflow(s) detected`
    );
  }

  // Env vars
  if (codebaseAnalysis.envVars.length > 0) {
    lines.push(
      `${codebaseAnalysis.envVars.length} environment variables from .env.example`
    );
  }

  // Project docs
  if (codebaseAnalysis.projectDocs.length > 0) {
    const docNames = codebaseAnalysis.projectDocs.map(
      (d: ExistingRule) => d.source
    );
    lines.push(`Project docs found: ${docNames.join(", ")}`);
  }

  // Conventions count (rough proxy: existing rules + stack items)
  const conventionCount =
    codebaseAnalysis.existingRules.length +
    codebaseAnalysis.buildCommands.length +
    codebaseAnalysis.lintCommands.length;
  if (conventionCount > 0) {
    lines.push(`${conventionCount} project conventions extracted`);
  }

  // Retry / failure patterns from sessions
  if (sessionAnalysis && sessionAnalysis.retryCount > 0) {
    lines.push(
      `${sessionAnalysis.retryCount} prompt retries detected (failure patterns)`
    );
  }

  return lines.map((l) => `• ${l}`).join("\n");
}

// ---------------------------------------------------------------------------
// Formatters (analysis → readable text for the LLM prompt)
// ---------------------------------------------------------------------------

function formatGitAnalysis(g: GitAnalysis): string {
  const parts: string[] = ["### Git History Analysis\n"];

  parts.push(`- Total commits scanned: ${g.totalCommits}`);
  parts.push(`- Authors: ${g.authors.join(", ") || "none"}`);
  if (g.dateRange) {
    parts.push(
      `- Date range: ${g.dateRange.earliest} to ${g.dateRange.latest}`
    );
  }
  parts.push(
    `- Clean commit rate: ${(g.cleanCommitRate * 100).toFixed(1)}%`
  );

  // Fix chains
  if (g.fixChains.length > 0) {
    parts.push(`\n**Fix-After-Feature Chains (${g.fixChains.length}):**`);
    const shown = g.fixChains.slice(0, 30);
    for (const fc of shown) {
      const files = fc.sharedFiles.slice(0, 5).join(", ");
      const extra = fc.sharedFiles.length > 5 ? ` +${fc.sharedFiles.length - 5} more` : "";
      parts.push(
        `- "${fc.featureCommit.message}" → fix: "${fc.fixCommit.message}" (${fc.hoursBetween.toFixed(1)}h) | files: ${files}${extra}`
      );
    }
    if (g.fixChains.length > 30) {
      parts.push(`- ... and ${g.fixChains.length - 30} more`);
    }
  } else {
    parts.push("\nNo fix-after-feature chains detected.");
  }

  // Coupling rules
  if (g.couplingRules.length > 0) {
    parts.push(
      `\n**Co-Change Coupling Rules (${g.couplingRules.length}):**`
    );
    const shown = g.couplingRules.slice(0, 20);
    for (const cr of shown) {
      parts.push(
        `- ${cr.fileA} ↔ ${cr.fileB} | ` +
          `${cr.coOccurrences} co-occurrences, ` +
          `${(cr.couplingRate * 100).toFixed(0)}% coupling`
      );
    }
    if (g.couplingRules.length > 20) {
      parts.push(`- ... and ${g.couplingRules.length - 20} more`);
    }
  }

  // Hotspots
  if (g.hotspots.length > 0) {
    parts.push("\n**Hotspot Files (top 15):**");
    const shown = g.hotspots.slice(0, 15);
    for (const h of shown) {
      parts.push(
        `- ${h.path} | ${h.commitCount} commits, ${h.fixCount} fixes`
      );
    }
  }

  return parts.join("\n");
}

function formatSessionAnalysis(s: SessionAnalysis): string {
  const parts: string[] = ["### Pi Session Analysis\n"];

  if (s.totalSessions === 0) {
    parts.push("No pi session history available.");
    return parts.join("\n");
  }

  parts.push(`- Sessions analyzed: ${s.totalSessions}`);
  parts.push(`- Total messages: ${s.totalMessages}`);
  parts.push(`- User messages: ${s.totalUserMessages}`);
  parts.push(`- Avg turns per session: ${s.avgTurnsPerSession.toFixed(1)}`);
  parts.push(`- Retries detected: ${s.retryCount}`);
  parts.push(`- Tool errors: ${s.toolErrorCount}`);

  if (s.promptPatterns.length > 0) {
    parts.push("\n**Common Prompt Patterns:**");
    const shown = s.promptPatterns.slice(0, 15);
    for (const p of shown) {
      parts.push(
        `- "${p.pattern}" — ${p.count} times, avg ${p.avgTurns} turns`
      );
    }
  }

  return parts.join("\n");
}

function formatCodebaseAnalysis(c: CodebaseAnalysis): string {
  const parts: string[] = ["### Codebase Analysis\n"];

  // Stack
  parts.push("**Tech Stack:**");
  parts.push(`- Language: ${c.stack.language}`);
  if (c.stack.framework) parts.push(`- Framework: ${c.stack.framework}`);
  if (c.stack.orm) parts.push(`- ORM: ${c.stack.orm}`);
  if (c.stack.styling) parts.push(`- Styling: ${c.stack.styling}`);
  if (c.stack.stateManagement)
    parts.push(`- State management: ${c.stack.stateManagement}`);
  if (c.stack.packageManager)
    parts.push(`- Package manager: ${c.stack.packageManager}`);
  parts.push(`- Monorepo: ${c.stack.monorepo ? "yes" : "no"}`);

  if (c.testFramework) parts.push(`- Test framework: ${c.testFramework}`);

  // Build / lint commands
  if (c.buildCommands.length > 0) {
    parts.push("\n**Build Commands:**");
    for (const cmd of c.buildCommands) parts.push(`- ${cmd}`);
  }
  if (c.lintCommands.length > 0) {
    parts.push("\n**Lint Commands:**");
    for (const cmd of c.lintCommands) parts.push(`- ${cmd}`);
  }

  // Key directories
  if (c.keyDirectories.length > 0) {
    parts.push("\n**Key Directories:**");
    const shown = c.keyDirectories.slice(0, 20);
    parts.push(shown.join(", "));
  }

  // File patterns
  if (c.filePatterns.length > 0) {
    parts.push("\n**File Extension Distribution:**");
    const shown = c.filePatterns.slice(0, 10);
    for (const fp of shown) {
      parts.push(`- ${fp.extension}: ${fp.count} files`);
    }
  }

  // Existing rules
  if (c.existingRules.length > 0) {
    parts.push("\n**Existing AI Rules:**");
    for (const rule of c.existingRules) {
      // Include up to 2000 chars of each rule file.
      const preview =
        rule.content.length > 2000
          ? rule.content.slice(0, 2000) + "\n[...truncated]"
          : rule.content;
      parts.push(`\nSource: ${rule.source} (${rule.path})`);
      parts.push("```");
      parts.push(preview);
      parts.push("```");
    }
  }

  // Linter / formatter config
  if (c.linterConfig) {
    parts.push(`\n**Linter/Formatter Configuration:**`);
    parts.push(`- Tool: ${c.linterConfig.tool}`);
    parts.push(`- Config: ${c.linterConfig.configPath}`);
    parts.push("```");
    parts.push(c.linterConfig.content);
    parts.push("```");
  }

  // Import aliases
  const aliasEntries = Object.entries(c.importAliases);
  if (aliasEntries.length > 0) {
    parts.push("\n**Import Aliases (tsconfig paths):**");
    for (const [alias, target] of aliasEntries) {
      parts.push(`- ${alias} → ${target}`);
    }
  }

  // CI/CD workflows
  if (c.ciWorkflows.length > 0) {
    parts.push(`\n**CI/CD Workflows:**`);
    for (const wf of c.ciWorkflows) {
      parts.push(`\nWorkflow: ${wf.name} (${wf.path})`);
      parts.push("```yaml");
      parts.push(wf.content);
      parts.push("```");
    }
  }

  // Environment variables
  if (c.envVars.length > 0) {
    parts.push("\n**Required Environment Variables (.env.example):**");
    for (const v of c.envVars) {
      parts.push(`- ${v}`);
    }
  }

  // Project documentation
  if (c.projectDocs.length > 0) {
    parts.push("\n**Project Documentation:**");
    for (const doc of c.projectDocs) {
      const preview =
        doc.content.length > 3000
          ? doc.content.slice(0, 3000) + "\n[...truncated]"
          : doc.content;
      parts.push(`\nSource: ${doc.source} (${doc.path})`);
      parts.push("```markdown");
      parts.push(preview);
      parts.push("```");
    }
  }

  // Dependencies (top 30)
  if (c.stack.dependencies.length > 0) {
    parts.push("\n**Dependencies (top 30):**");
    parts.push(c.stack.dependencies.slice(0, 30).join(", "));
    if (c.stack.dependencies.length > 30) {
      parts.push(`... and ${c.stack.dependencies.length - 30} more`);
    }
  }

  return parts.join("\n");
}

// ---------------------------------------------------------------------------
// Utility
// ---------------------------------------------------------------------------

/** Remove leading indentation and trim surrounding whitespace. */
function trimBlock(text: string): string {
  const lines = text.split("\n");
  // Find minimum indentation (ignoring empty lines).
  let minIndent = Infinity;
  for (const line of lines) {
    if (line.trim().length === 0) continue;
    const match = line.match(/^(\s*)/);
    if (match && match[1].length < minIndent) {
      minIndent = match[1].length;
    }
  }
  if (!isFinite(minIndent)) minIndent = 0;
  return lines
    .map((l) => l.slice(minIndent))
    .join("\n")
    .trim();
}
